version: '3.5'
services:

  kong_old:
    image: ${OLD_KONG_IMAGE}
    command: "tail -f /dev/null"
    user: root
    depends_on:
      - db_postgres
      - db_cassandra
    healthcheck:
      test: ["CMD", "true"]
      interval: 1s
      timeout: 1s
      retries: 10
    environment:
      KONG_PG_HOST: localhost
      KONG_CASSANDRA_CONTACT_POINTS: localhost
      KONG_TEST_PG_HOST: localhost
      KONG_TEST_CASSANDRA_CONTACT_POINTS: localhost
    volumes:
      - ../../worktree/${OLD_KONG_VERSION}:/kong
    restart: on-failure
    network_mode: "host"

  db_postgres:
    image: postgres:9.5
    environment:
      POSTGRES_DBS: kong,kong_tests
      POSTGRES_USER: kong
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: on-failure
    stdin_open: true
    tty: true
    network_mode: "host"

  db_cassandra:
    image: cassandra:3.11
    environment:
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: on-failure
    network_mode: "host"

