name: Backport
on:
  pull_request_target:
    types: [closed, labeled] # runs when the pull request is closed/merged or labeled (to trigger a backport in hindsight)
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
  actions: write
jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@08bafb375e6e9a9a2b53a744b987e5d81a133191 # v2.1.1
        with:
          github_token: ${{ secrets.PAT }}
          pull_title: '[backport -> ${target_branch}] ${pull_title}'
          merge_commits: 'skip'
          copy_labels_pattern: ^(?!backport ).* # copies all labels except those starting with "backport "
          label_pattern: ^backport (release\/[^ ]+)$ # filters for labels starting with "backport " and extracts the branch name
          pull_description: |-
            Automated backport to `${target_branch}`, triggered by a label in #${pull_number}.
          copy_assignees: true
          copy_milestone: true
          copy_requested_reviewers: true
