name: Cherry Pick to remote repository
on:
  pull_request_target:
    types: [closed, labeled]
  issue_comment:
    types: [created]
jobs:
  cross-repo-cherrypick:
    name: Cherry pick to remote repository
    runs-on: ubuntu-latest
    # Only run when pull request is merged, or labeled
    # or when a comment containing `/cherry-pick` is created
    # and the author is a member, collaborator or owner
    if: >
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(fromJSON('["MEMBER", "COLLABORATOR", "OWNER"]'), github.event.comment.author_association) &&
        startsWith(github.event.comment.body, '/cherry-pick')
      )
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHERRY_PICK_TOKEN }}
      - name: Create backport pull requests
        uses: jschmid1/cross-repo-cherrypick-action@3a1397a827bee94e57e2065ee2d51bd220723d40
        with:
          token: ${{ secrets.CHERRY_PICK_TOKEN }}
          pull_title: '[cherry-pick -> ${target_branch}] ${pull_title}'
          merge_commits: 'skip'
          trigger_label: 'cherry-pick kong-ee' # trigger based on this label
          pull_description: |-
            Automated cherry-pick to `${target_branch}`, triggered by a label in https://github.com/${owner}/${repo}/pull/${pull_number} :robot:.
          upstream_repo: 'kong/kong-ee'
          branch_map: |-
            {
              "master": "master"
            }
