name: gateway-api-tests

on:
  repository_dispatch:
    types: [per-commit-test]

  workflow_dispatch:
    inputs:
      enable_verbose_response_logging:
        description: 'Enable response logging for debugging'
        required: false
        default: 'false'
      send_slack_results:
        description: 'Send test result notifications to slack'
        required: false
        default: 'true'
      target_test:
        description: 'Run only a single test by spec name, smoke, non-smoke or all tests'
        required: false
        default: 'all'
      control_plane_image:
        description: 'Docker Image for Tests'
        required: true
        default: 'kong/kong-gateway-internal:nightly-ubuntu'
      multiarch:
        description: 'Also run ARM64 test for the image'
        required: false
        type: boolean
        default: false
      is_kong_oss:
        description: 'Run tests for Kong OSS'
        required: false
        type: boolean
        default: false

  workflow_call:
    inputs:
      enable_verbose_response_logging:
        description: 'Enable response logging for debugging'
        required: false
        type: 'string'
        default: 'false'
      send_slack_results:
        description: 'Send test result notifications to slack'
        required: false
        type: 'string'
        default: 'false'
      target_test:
        description: 'Run only a single test by spec name, only smoke tests or all tests'
        required: false
        type: string
      control_plane_image:
        description: 'Docker Image for Tests'
        required: true
        type: string
      multiarch:
        description: 'Also run ARM64 test for the image'
        required: false
        type: boolean
        default: false
      is_kong_oss:
        description: 'Run tests for Kong OSS'
        required: false
        type: boolean
        default: false

env:
  GW_IMAGE: ${{ inputs.control_plane_image || 'kong/kong-gateway-internal:nightly-ubuntu' }}
  GW_DP_IMAGE: ${{ inputs.control_plane_image || 'kong/kong-gateway-internal:nightly-ubuntu' }}
  SEND_SLACK_RESULTS: ${{ github.event.inputs.send_slack_results }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN_PRIVATE_READ }}
  # if this is a push event, or it is pull request but not from a fork, and not from dependabot (dependabot does not use forks), then this PR will have access to secrets
  HAS_ACCESS_TO_SECRETS: ${{ github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && !contains(github.actor, 'dependabot')) }}

jobs:
  gateway_api_tests:
    defaults:
      run:
        working-directory: spec-ee/kong-api-tests
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 90
    env:
      GW_MODE: ${{ matrix.gateway_mode }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TEST_API_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_API_AWS_SECRET_ACCESS_KEY }}
      VERBOSE_RESPONSE_LOGS: ${{ inputs.enable_verbose_response_logging }}
      RUN_SPEC: ${{ inputs.target_test || 'all' }}
      IS_KONG_OSS: ${{ inputs.is_kong_oss || 'false' }}
    strategy:
      fail-fast: false
      matrix:
        gateway_mode: ['classic', 'hybrid']
        runs_on: ["${{ vars.RUNS_ON }}", "${{ fromJSON(inputs.multiarch && '[\"ubuntu-latest-arm64-kong\"]' || '[]') }}" ]
    name: ${{ inputs.target_test }} API test - ${{ matrix.gateway_mode }} mode on ${{ matrix.runs_on }} for ${{ inputs.control_plane_image }}

    steps:
      - name: Overwrite environment variables if workflow dispatch
        if: ${{ github.event.action == 'per-commit-test' }}
        run: |
          echo "GW_IMAGE=${{ github.event.client_payload.docker_image }}" >> $GITHUB_ENV
          echo "GW_DP_IMAGE=${{ github.event.client_payload.docker_image }}" >> $GITHUB_ENV

          GW_PR_HREF='${{ github.event.client_payload.href }}'
          if [ -n "$GW_PR_HREF" ]; then
            echo "Now testing: [${GW_PR_HREF}](${GW_PR_HREF})" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Checkout docker-compose-generator
        uses: actions/checkout@v4
        with:
          repository: Kong/gateway-docker-compose-generator
          path: spec-ee/kong-api-tests/gateway-docker-compose-generator
          token: ${{ secrets.TEST_API_GH_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GHA_DOCKERHUB_PULL_USER }}
          password: ${{ secrets.GHA_KONG_ORG_DOCKERHUB_PULL_TOKEN }}

      - name: Set domain.test to hostnames for ACME and otel file permissions
        run: echo "127.0.0.1 domain.test" | sudo tee -a /etc/hosts && cd gateway-docker-compose-generator/otel && chmod 666 file_exporter.json

      - name: Check for FIPS image
        run: |
          if ${{ contains(env.GW_IMAGE, 'fips') }}; then FIPS_MODE=on; else FIPS_MODE=off; fi;
          echo "FIPS_MODE=$FIPS_MODE" >> $GITHUB_ENV

          if [[ $IS_KONG_OSS == "true" ]]; then
            RUN_SPEC="oss"
          fi

          if [[ $RUN_SPEC == "smoke" || $RUN_SPEC == "custom-plugins" || $RUN_SPEC == 'all' || $RUN_SPEC == 'oss' ]]; then
            CUSTOM_PLUGIN=true
          else
            CUSTOM_PLUGIN=false
          fi

          echo "CUSTOM_PLUGIN_VAR=$CUSTOM_PLUGIN" >> $GITHUB_ENV
          echo "CUSTOM_PLUGIN is $CUSTOM_PLUGIN"
          echo "RUN_SPEC=$RUN_SPEC" >> $GITHUB_ENV
          echo "RUN_SPEC" is $RUN_SPEC


      - name: Start Gateway
        run: cd gateway-docker-compose-generator && make generate && cat docker-compose.yml && make start_ci
        env:
          EE_LICENSE: false
          GW_ENTERPRISE: ${{ env.IS_KONG_OSS == 'false' && true || false }}
          PKI: true
          INFLUXDB: ${{ env.IS_KONG_OSS == 'false' && true || false }}
          REDIS_MODE: standalone
          SWAGGER: true
          GW_HOST: localhost
          HCV: ${{ env.IS_KONG_OSS == 'false' && true || false }}
          JAEGER: true
          CUSTOM_CONFIG_ALL: "RLA_REDISU: redisuser; RLA_REDISP: redispassword; AWS_REGION: us-east-2; AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}; AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}; GCP_SERVICE_ACCOUNT: '${{ secrets.TEST_API_GCP_SERVICE_ACCOUNT }}'"
          KEYCLOAK: true
          STATUS_LISTEN: true
          PROMETHEUS: true
          WASM: true
          AZURE_VAULT: true
          APP_D: ${{ env.IS_KONG_OSS == 'false' && true || false }}
          AZURE_TENANT_ID: ${{ secrets.TEST_API_AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.TEST_API_AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.TEST_API_AZURE_CLIENT_SECRET }}
          # set CUSTOM_PLUGIN to false in case of amazonlinux-2 image
          CUSTOM_PLUGIN: ${{ endsWith(env.GW_IMAGE, 'amazonlinux-2') && 'false' || env.CUSTOM_PLUGIN_VAR }}
          ACME: true
          OTEL: true

      - name: Logs from Gateway Start
        if: failure()
        working-directory: gateway-docker-compose-generator
        run: |
          make logs || true
          make logs_package || true

      - name: Copy .npmrc
        run: cp .npmrc.ci .npmrc

      - name: Install Packages
        run: npm install --legacy-peer-deps

      - name: Install decK
        uses: kong/setup-deck@v1

      - name: Execute Gateway API Tests
        id: execute_tests
        continue-on-error: true
        run: |
          if [[ $RUN_SPEC == 'all' ]]; then
            npm run test-gateway;
          elif [[ $RUN_SPEC == 'smoke' ]]; then
            npm run test-smoke;
          elif [[ $RUN_SPEC == 'non-smoke' ]]; then
            npm run test-non-smoke;
          elif [[ $RUN_SPEC == 'oss' ]]; then
            npm run test-oss;
          else
            TEST_APP=gateway npm run test-spec --spec=$RUN_SPEC;
          fi
        env:
          AZURE_FUNCTION_KEY: ${{ secrets.TEST_API_AZURE_FUNCTION_KEY }}
          APPD_PASSWORD: ${{ secrets.TEST_API_APPD_PASSWORD }}


      - uses: datadog/junit-upload-github-action@c4b57b587ae0e3ed618a1f0e7a7d260cfde53032 # v1.4.0
        continue-on-error: true
        if: ${{ always() && env.HAS_ACCESS_TO_SECRETS == 'true' }} # upload test results even if the job fails
        with:
          api_key: ${{ secrets.DATADOG_API_KEY }}
          service: kong-ee-github-actions-ci
          files: spec-ee/kong-api-tests/results/
          extra-args: --xpath-tag test.suite=/testcase/@classname

      - name: Get Gateway Details
        if: ${{ always() }}
        continue-on-error: true
        id: get_gw_details
        run: |
          echo "gw_version=$(curl -H kong-admin-token:handyshake http://localhost:8001 | jq -r '.version')" >> $GITHUB_OUTPUT
          echo "git_commit_sha=$(docker inspect $GW_IMAGE | jq -r '.[].Config.Labels["org.opencontainers.image.revision"]')" >> $GITHUB_OUTPUT

      - name: Retry Failed E2E API Tests
        if: steps.execute_tests.outcome == 'failure'
        run: |
          if test -s failed-tests.txt; then
            npm run test-multiple -- --spec=$(cat failed-tests.txt)
          else
            echo -e "No failed test names were found, there is a different issue\nCheck the 'Execute Gateway API Tests' step for more details"
            exit 1
          fi
        env:
          AZURE_FUNCTION_KEY: ${{ secrets.TEST_API_AZURE_FUNCTION_KEY }}
          APPD_PASSWORD: ${{ secrets.TEST_API_APPD_PASSWORD }}
          TEST_APP: gateway

      - name: Send test results to Slack
        if: ${{ env.SEND_SLACK_RESULTS == 'true' && always() && github.ref == 'refs/heads/master' }}
        continue-on-error: true
        uses: ./.github/actions/gw-slack-results/
        with:
          gw_version: ${{ steps.get_gw_details.outputs.gw_version }}
          git_commit_sha: ${{ steps.get_gw_details.outputs.git_commit_sha }}
          gw_mode: ${{ matrix.gateway_mode }}
          job_status: ${{ job.status }}
          test_title: 'regular'
          slack_url: ${{ secrets.TEST_API_SLACK_WEBHOOK_URL }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        continue-on-error: true
        if: ${{ always() && env.HAS_ACCESS_TO_SECRETS == 'true' }} # upload test results even if the job fails
        with:
          name: gateway_api_${{ env.RUN_SPEC }}_test_results_${{ matrix.gateway_mode }}
          path: spec-ee/kong-api-tests/results/
          retention-days: 3
