name: Update test runtime statistics file for test scheduling
on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * SAT"
  push:
    branches:
      - feat/test-run-scheduler

jobs:
  process-statistics:
    name: Download statistics from GitHub and combine them
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Process statistics
        uses: Kong/gateway-test-scheduler/analyze@main
        with:
          workflow-name: build_and_test.yml
          test-file-runtime-file: .ci/runtimes.json
          artifact-name-regexp: test-rerun-info-\d+
